code/danidcareservices/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  resources :danids

end

code/danidcareservices/app/models/danid.rb
class Danid < ActiveRecord::Base
validates :title, presence: true, length: { minimum: 3, maximum: 50 }
validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

code/danidcareservices/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

code/danidcareservices/app/controllers/danids_controller.rb
class DanidsController < ApplicationController

def index
	
end
def new
	@danid = Danid.new
end

def create
	@danid = Danid.new(danid_params)
	if @danid.save
		flash[:notice] = "Article was successfully craated"
	redirect_to danid_path(@danid)
else
	render 'new'
end
end

def edit
	@danid = Danid.find(params[:id])
	
end
def update
	@danid = Danid.find(params[:id])
	if @danid.update(danid_params)
		flash[:notice] = "Article was successfully update"
		redirect_to danid_path(@danid)
	else
		render 'edit'
	end
end

def show
	@danid = Danid.find(params[:id])
	
end

def destroy
	@danid = Danid.find(params[:id])
	@danid.destroy
	flash[:notice] = "Article was successfully deleted"
	redirect_to danid_path
	
end

def delete
	
end

private

def danid_params 
	params.require(:danid).permit(:title, :description)
	
end

end

code/danidcareservices/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

code/danidcareservices/app/helpers/application_helper.rb
module ApplicationHelper
end

code/danidcareservices/app/helpers/welcome_helper.rb
module WelcomeHelper
end

code/danidcareservices/app/views/danids/_form.html.erb
	<% if @danid.errors.any? %>
	<ul>
	<h2> The following errors prevented the articles from getting created</h2>
		<% @danid.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
		</ul>
<% end %>

		<%= form_for(@danid, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			

			<div class="form_group">
			<div class="control-label col-sm-2">
			<%= f.label :title %>
			</div>

			<div class="col-sm-8">
			<%= f.text_field :title, class: "form-control", placeholder: "Title of Talent", autofocus: true %>
				
			</div>
</div><br/><br/><br/>



	<div class="form_group">
		<div class="control-label col-sm-2">
			<%= f.label :description %>
			</div>

		<div class="col-sm-8">
	<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Write a few words about your talent" %>
		</div>
	</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>


			<br/>
			<br/>
			
	<div class="form_group">
			<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit class: 'btn btn-primary btn-lg' %>
						<%= link_to "Cencle", danids_path, class: 'btn btn-success' %>

				</div>
			</div>
				<% end %>
		

code/danidcareservices/app/views/danids/edit.html.erb
	<% if @danid.errors.any? %>
	<ul>
	<h2> The following errors prevented the articles from getting created</h2>
		<% @danid.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
		</ul>
<% end %>

		<%= form_for(@danid, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			

			<div class="form_group">
			<div class="control-label col-sm-2">
			<%= f.label :title %>
			</div>

			<div class="col-sm-8">
			<%= f.text_field :title, class: "form-control", placeholder: "Title of Talent", autofocus: true %>
				
			</div>
</div><br/><br/><br/>



	<div class="form_group">
		<div class="control-label col-sm-2">
			<%= f.label :description %>
			</div>

		<div class="col-sm-8">
	<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Write a few words about your talent" %>
		</div>
	</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>


			<br/>
			<br/>
			
	<div class="form_group">
			<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit class: 'btn btn-primary btn-lg' %>
						<%= link_to "Cencle", danids_path, class: 'btn btn-success' %>

				</div>
			</div>
				<% end %>
		

code/danidcareservices/app/views/danids/new.html.erb
<%= render 'form' %>

code/danidcareservices/app/views/danids/show.html.erb
<p>
Title: <%= @danid.title %>
</p>

<p>

Description: <%= @danid.description %>
</p>

code/danidcareservices/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
	<ul>
		<li><%= msg %></li>
		</ul>
	<% end %>

code/danidcareservices/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Danidcareservices</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/messages' %>
<%= yield %>

</body>
</html>

code/danidcareservices/app/views/welcome/home.html.erb
<h1>refuge wise</h1>